name: Deploy and Delete Network CloudFormation Stack

on:
  workflow_dispatch:
    inputs:
      action:
        description: 'Choose action to perform'
        required: true
        default: deploy
        type: choice
        options:
          - deploy
          - delete

jobs:
  deploy:
    if: ${{ github.event.inputs.action == 'deploy' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1

      - name: Deploy CloudFormation Stack
        run: |
          PARAMS=$(jq -r '.[] | "\(.ParameterKey)=\(.ParameterValue)"' network-parameters.json | xargs)
          aws cloudformation deploy \
            --stack-name networkStack \
            --template-file network.yml \
            --parameter-overrides $PARAMS

  delete:
    if: ${{ github.event.inputs.action == 'delete' }}
    runs-on: ubuntu-latest

    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1

      - name: Delete CloudFormation Stack
        run: |
          aws cloudformation delete-stack --stack-name networkStack
          # Optional: Wait until deletion completes
          aws cloudformation wait stack-delete-complete --stack-name networkStack
