name: Deploy Network CloudFormation Stack

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1

      - name: Deploy CloudFormation Stack
        run: |
          set +e
          PARAMS=$(jq -r '.[] | "\(.ParameterKey)=\(.ParameterValue)"' network-parameters.json | xargs)
          aws cloudformation deploy \
            --stack-name networkStack \
            --template-file network.yml \
            --parameter-overrides $PARAMS \
            --debug
          DEPLOY_EXIT_CODE=$?
          if [ $DEPLOY_EXIT_CODE -ne 0 ]; then
            echo "CloudFormation deploy failed. Fetching recent stack events..."
            aws cloudformation describe-stack-events --stack-name networkStack
          fi
          exit $DEPLOY_EXIT_CODE
      
